name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lipo-macos:
    name: Lipo macos
    # aarch64 runner
    runs-on: macos-14
    env:
      SCCACHE_GHA_ENABLED: "true"
      RUSTC_WRAPPER: "sccache"
      CC_ENABLE_DEBUG_OUTPUT: "1"
    steps:
      - uses: mozilla-actions/sccache-action@v0.0.5
        with:
          version: "v0.7.4" 
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.0.1'
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: x86_64-apple-darwin

      - name: Lipo macos
        run: |
          uname -a
          xcodebuild -version
          xcrun --sdk macosx --show-sdk-path
          sccache --version

          cargo -vv rustc --target aarch64-apple-darwin --package repro --profile dev --crate-type=staticlib
          cargo -vv rustc --target x86_64-apple-darwin --package repro --profile dev --crate-type=staticlib
          lipo -archs target/aarch64-apple-darwin/debug/librepro.a
          lipo -archs target/x86_64-apple-darwin/debug/librepro.a
